name: test uploading artifact

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my-artifact.txt
      - name: Run Script
        run: |
          cat my-artifact.txt