name: test uploading artifact

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./my-artifact.txt